### PR TITLE
Subcraft Rotation Against Relative Point

### PR DESCRIPTION
**Pull request by mwkaicz**
... works also like remote controller for Subcraft Rotate

### CODE REVIEW

**Comment by mwkaicz** [comment]
added option specify relative point for Subcraft Rotation improves maneuverability without leaving helm position)

Sign format:

1. Subcraft Rotate
2. craft_name
3. {empty row}
4. x,y,z

new coords are calculated by sign facing
-x = left,   +x = right, -y = bottom, +y = up, -z = backward, +z forward

**Comment by msummers123** [comment]
Does this include an option to disable this functionality? We had to remove off-center rotation because players were abusing it.

**Comment by mwkaicz** [comment]
It's only for Subcraft Rotate, not classic [helm] ... and if you will keep 4th row empty, it work's like usually

**Comment by mwkaicz** [comment]
It works good and it's possible use it for ship bridges or small gates ...  but after few hours of testing, I must decide, that there should be some limit for distance of the center of rotation. So closing this, I'll make some craftType property for this.

**Comment by msummers123** [comment]
Ok, good idea though. I know I have had some turrets I just couldn't get to work because the subcraft rotate sign had to be in the exact center.

**Pull request closed without merging**
