### PR TITLE
Arrows "pop" wool

### PR DESCRIPTION
**Pull request by Pocketkid2**

### CODE REVIEW

**Comment by mwkaicz** [comment]
What about to add some option to allow/deny this? I don't like changes without chance to make a choice If want to use it.

**Comment by mwkaicz** [comment]
And what's worse it affect all wool not only on active craft ... that's bad

**Comment by Pocketkid2** [comment]
I'll see if I can add those.

**Comment by msummers123** [comment]
Yeah, I dunno about this. I might be OK with some kind of optional "rocket launcher" type thing, as long as it could be disabled and wasn't game breaking. But I think we need some serious restrictions on this.

**Comment by msummers123** [comment]
Oh, one other thing to think about is the implications of world protection plugins. We need to make sure that anything we add that can destroy blocks can be prevented by world protection plugins. For example, the ability of fireballpenetration setting checks to see if the fire event was canceled, which means a world protection plugin blocked it. Otherwise people can destroy protected parts of a server.

**Comment by Pocketkid2** [comment]
Sounds logical.

**Pull request closed without merging**
