### PR TITLE
Add Release Arguments, an Obstruction Sound, a day of the week config to siege, a log event to repair, a Status Sign, and commands for siege to run once started and ended.

### PR DESCRIPTION
**Pull request by Thomdare**
This will add the ability for staff to release specific player's ships, or use the -a parameter to release all crafts.

### CODE REVIEW

**Comment by TylerS1066** [comment]
@msummers123 Looks good to me


@Thomdare Could you compile and send me a jar for testing this out?

**Comment by Thomdare** [comment]
@TylerS1066 No problem. I'll get it to you in about two hours, I'm going out. But if I can't get it to you by then it'll have o be later since I'm just going to be home for a bit

**Comment by msummers123** [comment]
Wow, I didn't see any of the title changes (it doesn't send notifications of that) and thought this was just a small thing to add the obstruction sounds! This is great, I'll take a look at it early next week.

**Comment by msummers123** [comment]
One more quick thing before I get back to work: If I do a video announcing all these awesome new changes, how do you want your name to be credited in the video? IE: what name should I use?

**Comment by Thomdare** [comment]
@msummers123 Thomdare is fine, I usually keep it the same for all games and applications. (So it's my pmc, mc forums, WoWs, enjin, and minecraft username)

**Comment by msummers123** [comment]
Ok, there were a bunch of conflicts, so I put in these changes manually. Everything should be in now. Unfortunately, this means you will need to re-pull or re-fork the plugin to keep your own repository up to date. Wait on doing this until I know everything is good, so if we need to refer back to your version we still can.

**Pull request closed without merging**
