### PR TITLE
Deprecate .craft files.

### PR DESCRIPTION
**Pull request by alexknvl**
Rationale: text editors are not configured by default to recognize `.craft` as YAML files, which might cause some problems for inexperienced server owners who don't know how to configure their text editors (lol). And there is simply no good reason to have a custom file format name.

### CODE REVIEW

**Comment by mwkaicz** [comment]
Hay man, some people and some other plugins, web pages etc. depends on `.craft` extension

**Comment by alexknvl** [comment]
That's why it's a deprecation, not a sudden removal of support ;) Just a warning to make people switch to YAML, and update their plugins to support `.yaml` as well as `.craft`.

**Comment by mwkaicz** [comment]
sorry, but by this theory it was deprecated ever and nobody have problem with it, .yaml has never supported .craft extension but nobody care about it. it's the way how earmark crafts from other yaml files and it's there from first AJStriker commit. There is really no reason for this. And for those people who don't want convert it in to .yaml this causes spam of many rows (f.e: in our case over 50 rows) each server restart.

**Comment by msummers123** [comment]
Thanks for trying to help out, but I'm afraid I would have to agree that I don't see this as a beneficial change.

**Pull request closed without merging**
